/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CameraBodyType = "compact" | "dslr" | "mirrorless";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ModelCategory = "camera" | "lens";

export type SellerType = "private" | "store";

export type SensorFormat = "aps_c" | "full_frame" | "medium_format" | "micro_four_thirds" | "one_inch";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Brands {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface CameraSpecs {
  body_type: CameraBodyType;
  has_mechanical_shutter: Generated<boolean>;
  megapixels: number | null;
  model_id: string;
  sensor_format: SensorFormat;
}

export interface LensSpecs {
  filter_thread_mm: number | null;
  focal_max_mm: number;
  focal_min_mm: number;
  has_stabilization: Generated<boolean>;
  max_aperture: number;
  model_id: string;
}

export interface ModelAliases {
  alias: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_canonical: Generated<boolean>;
  model_id: string;
  normalized: Generated<string>;
}

export interface Models {
  brand_id: string;
  category: ModelCategory;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mount_id: string | null;
  name: string;
  release_year: number | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface Mounts {
  brand_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  id: Generated<string>;
  seller_type: Generated<SellerType>;
  store_name: string | null;
  store_slug: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  brands: Brands;
  camera_specs: CameraSpecs;
  lens_specs: LensSpecs;
  model_aliases: ModelAliases;
  models: Models;
  mounts: Mounts;
  sessions: Sessions;
  users: Users;
}
