/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CameraBodyType = "compact" | "dslr" | "mirrorless" | "rangefinder" | "slr";

export type CosmeticCondition = "damaged" | "excellent" | "good" | "mint" | "well_used";

export type FunctionalCondition = "faulty" | "fully_working" | "minor_issues";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Inclusion = "body_cap" | "case" | "charger" | "lens_hood" | "manual" | "memory_card" | "oem_battery" | "original_box" | "rear_cap" | "receipt" | "strap" | "third_party_battery";

export type ListingStatus = "active" | "draft" | "removed" | "sold";

export type ModelCategory = "accessory" | "camera" | "lens";

export type SensorFormat = "aps_c" | "full_frame" | "medium_format" | "micro_four_thirds" | "one_inch";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Brand {
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface CameraSpec {
  battery_model: string | null;
  body_type: CameraBodyType;
  depth_mm: number | null;
  has_ibis: boolean | null;
  has_mechanical_shutter: Generated<boolean>;
  height_mm: number | null;
  is_film: Generated<boolean>;
  megapixels: number | null;
  model_id: string;
  records_4k: boolean | null;
  sensor_format: SensorFormat;
  weather_sealed: boolean | null;
  weight_grams: number | null;
  width_mm: number | null;
}

export interface City {
  id: Generated<string>;
  name: string;
  position: number;
  slug: string;
}

export interface LensSpec {
  diameter_mm: number | null;
  filter_thread_mm: number | null;
  focal_max_mm: number;
  focal_min_mm: number;
  has_stabilization: Generated<boolean>;
  length_mm: number | null;
  max_aperture: number;
  model_id: string;
  weight_grams: number | null;
}

export interface Listing {
  city_id: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  price_cents: number | null;
  published_at: Timestamp | null;
  seller_id: string;
  status: Generated<ListingStatus>;
  updated_at: Generated<Timestamp>;
}

export interface ListingInclusion {
  inclusion: Inclusion;
  listing_item_id: string;
}

export interface ListingItem {
  cosmetic_condition: CosmeticCondition;
  created_at: Generated<Timestamp>;
  functional_condition: FunctionalCondition;
  id: Generated<string>;
  listing_id: string;
  model_id: string;
  position: number;
  price_cents: number | null;
  shutter_count: number | null;
  sold_separately: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface ListingPhoto {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  listing_id: string;
  position: number;
  storage_key: string;
}

export interface Model {
  brand_id: string;
  category: ModelCategory;
  display_name: string;
  id: Generated<string>;
  mount_id: string | null;
  name: string;
  normalized: Generated<string | null>;
  release_year: number | null;
  slug: string;
}

export interface Mount {
  brand_id: string | null;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  user_id: string;
}

export interface Store {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface User {
  city_id: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  id: Generated<string>;
  password_hash: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  brand: Brand;
  camera_spec: CameraSpec;
  city: City;
  lens_spec: LensSpec;
  listing: Listing;
  listing_inclusion: ListingInclusion;
  listing_item: ListingItem;
  listing_photo: ListingPhoto;
  model: Model;
  mount: Mount;
  session: Session;
  store: Store;
  user: User;
}
